name: GitHub Pages

on:
  push:
   branches:
    - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: yarn
      
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v2

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            starters/gatsby-starter-aoi-theme/public
            starters/gatsby-starter-aoi-theme/.cache
          key: ${{ runner.os }}-gatsby-build-${{ hashFiles('starters/gatsby-starter-aoi-theme/public') }}
          restore-keys: |
            ${{ runner.os }}-gatsby-build-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build theme
        run: yarn run build

      - name: Build starter
        run: yarn run build:starter

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./starters/gatsby-starter-aoi-theme/public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
