name: Test
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - develop
    paths:
      - package.json
      - packages/*/src/**
      - packages/*/package.json
      - .github/workflows/**

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Nodes
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'yarn'
      
      - name: Install dependencies
        run: yarn install --immutable

      - name: Test
        run: yarn run test

      - name: Build Theme
        run: yarn run build:theme
      
      - name: Build Blog Theme
        run: yarn run build:theme-blog
